### ISSUE TITLE
EGL  library and color space issue

### ISSUE THREAD

**Issue by SaharHusseini** [thu-ml/AT3D#2]
Hello,

I tried to run the "bash ./run_attacks_2D_MIM.sh" file, and, since I can not install  EGL on my computer, I needed to change "RasterizeGLContext" to "RasterizeCudaContext" in the following file:
"AT3D/AT3D/utils/nvdiffrast.py"

I attached the resulting image, which I think has weird color in the attacked areas. 

Could you please tell me if the color is ok? If not, do you have some suggestions for modifying the color space just for the attacked parts?
![model_ResNet50_eps_40 0_iters_400_attack_BIM_method_2d_bg_0](https://github.com/thu-ml/AT3D/assets/93087155/34b44599-c930-487d-8ea0-cb006a7fda90)

BR,
Sahar

**Comment by elenacliu** [comment]
The 1st problem: there may be a problem if you cannot install EGL, since I directly used the code `AT3D/AT3D/utils/nvdiffrast.py` in [https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/master/util/nvdiffrast.py](https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/master/util/nvdiffrast.py) and I'm not sure how to solve this problem. But it seems that the solution you adopted works. Can you make a PR to my repo?

The 2nd problem: 2D attack using MIM methods is one of the baselines in our work, and you can refer the paper [here](https://arxiv.org/pdf/2106.15058.pdf). The results it got are not so "realistic" and a little noisy.

**Comment by elenacliu** [comment]
It seems that pr1 #3 can resolve the first environment setup problem, so close the issue now.
